### ISSUE TITLE
OMM 5.2 deletes view composition from 4.10 on initial load

### ISSUE THREAD

**Issue by davetsay** [NASA-AMMOS/openmct-mcws#171]
**Describe the defect**

When transitioning to OMM 5.2 from OMM 4.10, several views are not opening successfully, appearing instead as blank views. Upon investigation, the modification date of these views updates to the first time they are opened in version 5.2:

Additionally, the composition of these views appears to be empty.

**Expected behavior**

Views should not disappear when transitioning to a newer version of OMM.

**Steps To Reproduce**
1. take an OMM 4.10 persistence store and use it in OMM 5.2
2. Go through the views to see there are some missing

**Comment by jvigliotta** [comment]
Investigated. This issue stems from older versions of OMM not removing items from display/flexible layout configuration property on the domainObject, but removing it from the composition (ex. deleting from the tree). Thus the items would still show in 4.10 but when opened in 5.2, the configuration items were wiped out as they do not exist in the composition, which is the expected behavior. A script will be used to populate the composition of these older domainObjects based on the items in the configuration before moving to 5.2.
